class AppConnectionError(Exception):
    """Исключение, вызываемое при невозможности подключения к приложению."""
